/** @type {import('jest').Config} */
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/controllers/**',
    '!**/*.controller.ts',
    '!**/*.controller.spec.ts',
    '!**/*.module.ts',
    '!**/*.dto.ts',
    '!**/*.dto.spec.ts',
    '!**/*.gateway.ts',
    '!**/*.gateway.spec.ts',
    '!**/*.decorator.ts',
    '!**/*.decorator.spec.ts',
    '!**/*.guard.ts',
    '!**/*.guard.spec.ts',
    '!**/*.strategy.ts',
    '!**/*.strategy.spec.ts',
    '!**/*.middleware.ts',
    '!**/*.middleware.spec.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coveragePathIgnorePatterns: [
    '<rootDir>/controllers/',
    '.controller.ts$',
    '.module.ts$',
    '.dto.ts$',
    '.gateway.ts$',
    '.decorator.ts$',
    '.guard.ts$',
    '.strategy.ts$',
    '.middleware.ts$',
    '<rootDir>/main.ts',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/.*/controllers/',
    '.controller.spec.ts$',
    '.module.spec.ts$',
    '.dto.spec.ts$',
    '.gateway.spec.ts$',
    '.decorator.spec.ts$',
    '.guard.spec.ts$',
    '.strategy.spec.ts$',
    '.middleware.spec.ts$',
  ],

  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
};
